### PR TITLE
Use latest ember-watson

### PR DESCRIPTION
**Pull request by devinus**

### CODE REVIEW

**Comment by mrb** [comment]
@devinus Thank you for this! We're in the process of evaluating the changes.

**Comment by devinus** [comment]
I'm not sure what the problem is on CircleCI. :-/

**Comment by mrb** [comment]
@devinus That's our internal stuff no worries there.

**Comment by dillonwelch** [comment]
Any updates on this? The version of `ember-watson` that you are currently using is throwing an error for something that it really shouldn't (and it doesn't on the latest `ember-watson`)

In particular, we have this bit of code in a spec:
`answerFor(/*answerGroup, question*/){` 
and CodeClimate it saying that it should actually be:
`answerFor/*answerGroup, question*/() {`

Opinions on the commented out arguments aside, we don't want CodeClimate complaining about it :smile:

**Comment by mrb** [comment]
Update: I'm working on a branch to bring watson up to speed with the changes necessary to make this run on Code Climate. The current state of that branch is here https://github.com/abuiles/ember-watson/compare/master...mrb:all_dry_run - I'm on vacation until 1/4 and will resume work then. /c @oniofchaos @devinus

**Comment by dillonwelch** [comment]
@mrb any progress on your ember-watson branch?

**Comment by mrb** [comment]
@oniofchaos Hey - sorry about that, I got kind of stalled on this. The branch above is still up to date - I'll shoot you an email, maybe we can chat further.

**Comment by tim-evans** [comment]
Hi @mrb, is there any work that could be done to get this to the most recent version of ember-watson? Cheers!

**Comment by mrb** [comment]
@tim-evans yes! Shoot me an email mrb@codeclimate.com

**Comment by dblandin** [comment]
Closing in favor of https://github.com/codeclimate-community/codeclimate-watson/pull/7

**Pull request closed without merging**
